Alters tmux-sass-watch and tmux-site-watch to use tmux-split.

diff --git a/.bash_lib/tmux-sass-watch b/.bash_lib/tmux-sass-watch
--- a/.bash_lib/tmux-sass-watch
+++ b/.bash_lib/tmux-sass-watch
@@ -11,19 +11,10 @@
 #                   sass-watch pane.
 #
 
+source $(dirname $0)/tmux-split
+[[ ! "$?" = "0" ]] && echo "[WARN] tmux-status-window not found." && exit
 
-if ((tmux list-panes -F "#{pane_start_command}" | grep ^sass-watch$ )>/dev/null) ; then
-    kill $(ps -o "%p%c" $(tmux list-panes -F "#{pane_pid}") | grep sass-watch$ | awk "{ print $1 }")
-else # Otherwise, it isn't yet running, start it:
-    # If site-watch is running, share the screen with it:
-    if ((ps -o "%c" $(tmux list-panes -F "#{pane_pid}") | grep ^site-watch$ )>/dev/null) ; then
-        tmux select-pane -t bottom
-        tmux split-window -c "$(tmux display-message -p -F "#{pane_current_path}" -t0)" -h "sass-watch"
-        tmux select-pane -U
-    else # Otherwise, just be on the bottom:
-        tmux split-window -c "$(tmux display-message -p -F "#{pane_current_path}" -t0)" -v -l 5 "sass-watch"
-        tmux select-pane -U
-    fi
-fi
+toggle_split "sass-watch" "site-watch"
+
 
 # vim:set ft=sh fdm=marker:
diff --git a/.bash_lib/tmux-site-watch b/.bash_lib/tmux-site-watch
--- a/.bash_lib/tmux-site-watch
+++ b/.bash_lib/tmux-site-watch
@@ -11,19 +11,10 @@
 #                   site-watch pane.
 #
 
+source $(dirname $0)/tmux-split
+[[ ! "$?" = "0" ]] && echo "[WARN] tmux-status-window not found." && exit
 
-if ((tmux list-panes -F "#{pane_start_command}" | grep ^site-watch$ )>/dev/null) ; then
-    tmux send-keys -t $(tmux list-panes -F "#{pane_id} #{pane_start_command}" | grep site-watch$ | awk "{ print $1 }") C-c
-else # Otherwise, it isn't yet running, start it:
-    # If sass-watch is running, share the screen with it:
-    if ((ps -o "%c" $(tmux list-panes -F "#{pane_pid}") | grep ^sass-watch$ )>/dev/null) ; then
-        tmux select-pane -t bottom
-        tmux split-window -c "$(tmux display-message -p -F "#{pane_current_path}" -t0)" -h "site-watch"
-        tmux select-pane -U
-    else # Otherwise, just be on the bottom:
-        tmux split-window -c "$(tmux display-message -p -F "#{pane_current_path}" -t0)" -v -l 5 "site-watch"
-        tmux select-pane -U
-    fi
-fi
+toggle_split "site-watch" "sass-watch"
+
 
 # vim:set ft=sh fdm=marker:
